<a href="https://colab.research.google.com/github/HuynhAnhTai0207/MachineLearning_20130388_HuynhAnhTai/blob/master/Lab_5_20130388_HuynhAnhTai.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# This lab is to deal with **SVM** to classification tasks and compare its performance with other competitive algorithms. In general, **SVM** is one of the most popular and widely used supervised machine learning algorithms.

*   **Deadline: 23:59, 17/03/2023**



# Import libraries

In [1]:
from sklearn import datasets
from sklearn import svm
from prettytable import PrettyTable
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from prettytable import MSWORD_FRIENDLY
import pandas as pd

#Task 1. 
For breast cancer dataset (https://tinyurl.com/3vme8hr3) which could be loaded from datasets in sklearn as follows:

```
#Import scikit-learn dataset library
from sklearn import datasets

#Load dataset
cancer = datasets.load_breast_cancer()
```

*   1.1.	Apply SVM algorithm to above dataset using linear kernel.
*   1.2.	Compare the obtained results with other competitive algorithms (Logistic Regression, Decision Tree, kNN) based on metrics: accuracy, precision, recall, f1 measures.



In [2]:
from sklearn.metrics._plot.confusion_matrix import confusion_matrix
import prettytable
cancer = datasets.load_breast_cancer()
X = cancer['data']
y = cancer['target']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

#SVM
SVM = svm.SVC(kernel='linear')
SVM.fit(X_train, y_train)
y_pred_svm = SVM.predict(X_test)
accuracy_svm = accuracy_score(y_test, y_pred_svm)
precision_svm = precision_score(y_test, y_pred_svm)
recall_svm = recall_score(y_test, y_pred_svm)
f1_svm = f1_score(y_test, y_pred_svm)
cm = confusion_matrix(y_test, y_pred_svm)
print(cm)

[[ 57   6]
 [  2 106]]


In [3]:
#Logistic Regression
classifier = LogisticRegression()
classifier.fit(X_train,y_train)
y_pred_lr = classifier.predict(X_test)
accurary_lr = accuracy_score(y_test,y_pred_lr)
precision_lr = precision_score(y_test,y_pred_lr)
recall_lr = recall_score(y_test, y_pred_lr)
f1_lr = f1_score(y_test, y_pred_lr)
cm_lr = confusion_matrix(y_test, y_pred_lr)
print(cm_lr)

[[ 57   6]
 [  3 105]]


/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [4]:
# Decision tree algorithm
dtc = DecisionTreeClassifier(random_state=42)
dtc.fit(X_train,y_train)
pred_labels_dtc = dtc.predict(X_test)
accurary_dtc = accuracy_score(y_test,pred_labels_dtc)
precision_dtc = precision_score(y_test,pred_labels_dtc)
recall_dtc = recall_score(y_test, pred_labels_dtc)
f1_dtc = f1_score(y_test, pred_labels_dtc)
cm_dtc = confusion_matrix(y_test, pred_labels_dtc)
print(cm_dtc)

[[ 56   7]
 [  0 108]]


In [6]:
#kNN
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train,y_train)
y_pred_knn = dtc.predict(X_test)
accurary_knn = accuracy_score(y_test,y_pred_knn)
precision_knn = precision_score(y_test,y_pred_knn)
recall_knn = recall_score(y_test, y_pred_knn)
f1_knn = f1_score(y_test, y_pred_knn)
cm_knn = confusion_matrix(y_test, y_pred_knn)
print(cm_knn)

[[ 56   7]
 [  0 108]]


In [7]:
t = PrettyTable(['algorithm', 'accurary_score','precision_score','recall_score','f1_score'])
accurary_lr = accuracy_score(y_test,y_pred_lr)
precision_lr = precision_score(y_test,y_pred_lr)
recall_lr = recall_score(y_test, y_pred_lr)
f1_lr = f1_score(y_test, y_pred_lr)

t.add_row(['SVM',round(accuracy_svm,2),round(precision_svm,2),round(recall_svm,2),round(f1_svm,2)])
t.add_row(['Logistic Regression',accurary_lr,precision_lr,recall_lr,f1_lr])
t.add_row(['Decision Tree',accurary_dtc,precision_dtc,recall_dtc,f1_dtc])
t.add_row(['KNN',accurary_knn,precision_knn,recall_knn,f1_knn])

print(t)


+---------------------+--------------------+--------------------+--------------------+--------------------+
|      algorithm      |   accurary_score   |  precision_score   |    recall_score    |      f1_score      |
+---------------------+--------------------+--------------------+--------------------+--------------------+
|         SVM         |        0.95        |        0.95        |        0.98        |        0.96        |
| Logistic Regression | 0.9473684210526315 | 0.9459459459459459 | 0.9722222222222222 | 0.9589041095890412 |
|    Decision Tree    | 0.9590643274853801 | 0.9391304347826087 |        1.0         | 0.968609865470852  |
|         KNN         | 0.9590643274853801 | 0.9391304347826087 |        1.0         | 0.968609865470852  |
+---------------------+--------------------+--------------------+--------------------+--------------------+


#Task 2. 

*   1.1.	Perform SVM algorithm to **Iris dataset** using **linear kernel**.
*   1.2.	Compare the obtained results in 1.1 with SVM using other kernels (**Polynomial Kernel, Gaussian Kernel, Sigmoid Kernel, Radial Basis Function Kernel**). Some metrics could be used: accuracy, precision, recall, f1 measures





In [8]:
data = datasets.load_iris()
X = data['data']
y = data['target']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)



In [9]:
poly = svm.SVC(kernel = 'poly')
poly.fit(X_train,y_train)
y_pred_poly = poly.predict(X_test)
accurary_poly = accuracy_score(y_test,y_pred_poly)
cm_poly = confusion_matrix(y_test, y_pred_poly)
print(cm_poly)

[[14  0  0]
 [ 0 17  1]
 [ 0  0 13]]


#Task 3. 
Compare the performance of selected classification algorithms (Decision Tree, kNN, Logistic Regression) and SVM (using different kernels) with mnist dataset based on accuracy, precision, recall, f1 measures.


In [12]:

mnist = fetch_openml('mnist_784')
X, y = mnist['data'], mnist['target']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


/usr/local/lib/python3.9/dist-packages/sklearn/datasets/_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


#Task 4. 
Compare the performance of selected classification algorithms (Decision Tree, kNN, Logistic Regression) and SVM (using different kernels) with **credit card dataset** based on accuracy, precision, recall, f1 measures.

*   Give some comments on the obtained results
*   Identify issues with dataset, and propose the solutions to these issues



In [11]:
from sklearn.impute import SimpleImputer 
import numpy as np
import pandas as pd

from google.colab import drive
drive.mount('/content/gdrive')
%cd '/content/gdrive/MyDrive/Marching-Learning/lab5'

data = pd.read_csv('creditcard.csv')
r = 234387/2
x = data.floc[: int(r),:]
x

Mounted at /content/gdrive
/content/gdrive/MyDrive/Marching-Learning/lab5


AttributeError: ignored

#Finally,
Save a copy in your Github. Remember renaming the notebook.